# Generated by Django 4.2.7 on 2025-08-02 05:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain name for the tenant.', max_length=253, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary domain for the tenant.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this domain is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'db_table': 'tenants_domain',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the tenant.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the tenant.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the tenant.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for the tenant.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone for the tenant.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address of the tenant.')),
                ('city', models.CharField(blank=True, help_text='City of the tenant.', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/province of the tenant.', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country of the tenant.', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code of the tenant.', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific settings stored as JSON.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the tenant.')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'db_table': 'tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invited user.', max_length=254)),
                ('role', models.CharField(choices=[('user', 'User'), ('tenant_admin', 'Tenant Admin')], default='user', help_text='Role to assign to the invited user.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Status of the invitation.', max_length=20)),
                ('token', models.CharField(help_text='Unique token for the invitation.', max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires.')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this invitation is for.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'tenant invitation',
                'verbose_name_plural': 'tenant invitations',
                'db_table': 'tenants_tenant_invitation',
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['name'], name='tenants_ten_name_87437c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this domain belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['email'], name='tenants_ten_email_76a502_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['status'], name='tenants_ten_status_04757b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['token'], name='tenants_ten_token_f159f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['expires_at'], name='tenants_ten_expires_f5892a_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain'], name='tenants_dom_domain_6df599_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['is_primary'], name='tenants_dom_is_prim_bbdf73_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['is_active'], name='tenants_dom_is_acti_b6d78c_idx'),
        ),
    ]
